// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2EoT3298oieFMG-jOYIf1miucM5JEkwM',
    appId: '1:1034386858837:web:90edcf0a0ad58f3689c5dc',
    messagingSenderId: '1034386858837',
    projectId: 'rakshak-1',
    authDomain: 'rakshak-1.firebaseapp.com',
    storageBucket: 'rakshak-1.appspot.com',
    measurementId: 'G-150LC88VR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaXESxbs4Hzf1xlGPdwfRB89sltxXBuNc',
    appId: '1:1034386858837:android:2b6f42f98b60cae389c5dc',
    messagingSenderId: '1034386858837',
    projectId: 'rakshak-1',
    storageBucket: 'rakshak-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpk2G4pCg0isEtmfAOcg0udL5yG0CUBsQ',
    appId: '1:1034386858837:ios:892b0de7e5e81d0c89c5dc',
    messagingSenderId: '1034386858837',
    projectId: 'rakshak-1',
    storageBucket: 'rakshak-1.appspot.com',
    iosClientId: '1034386858837-vn6nh97k1qgk2ufbnp464u0p6mioud3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.rakshak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpk2G4pCg0isEtmfAOcg0udL5yG0CUBsQ',
    appId: '1:1034386858837:ios:892b0de7e5e81d0c89c5dc',
    messagingSenderId: '1034386858837',
    projectId: 'rakshak-1',
    storageBucket: 'rakshak-1.appspot.com',
    iosClientId: '1034386858837-vn6nh97k1qgk2ufbnp464u0p6mioud3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.rakshak',
  );
}
